### ISSUE TITLE
having trouble running on ubuntu 16

### ISSUE THREAD

**Issue by gerrymcjr** [malikshubham827/get-me-through#2]
here are the prompt from running the npm install 
(get-me-through) gerrymac@ubuntu:~/env/get-me-through$ npm install

> uws@0.14.5 install /home/gerrymac/env/get-me-through/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

npm WARN get_me_through@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 374 packages in 29.203s
 npm start
(get-me-through) gerrymac@ubuntu:~/env/get-me-through$ npm start

> get_me_through@1.0.0 start /home/gerrymac/env/get-me-through
> node ./bin/www

module.js:487
    throw err;
    ^

Error: Cannot find module '/home/gerrymac/env/get-me-through/bin/www'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! get_me_through@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the get_me_through@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gerrymac/.npm/_logs/2017-07-25T03_58_13_794Z-debug.log

i followed every step of the installation am i doing siomething wrong?

**Comment by malikshubham827** [comment]
Have you googled about these warnings? I have found some comment which may be helpful
[comment node-gyp](https://github.com/nodejs/node-gyp/issues/809#issuecomment-155019383)
[comment](https://github.com/facebookincubator/create-react-app/issues/2652#issuecomment-311617553)

According to the error: it is not able to find the ./bin/www file which I just saw that I have not added in the repo. I ignored the bin folder in starting as it has many files which are auto generated and not worth to upload it to github.

So the solution is, in the root of your project you would have a folder named `bin` go into it( if not create one) and paste this file (without extensions): [www] (https://gist.github.com/malikshubham827/439cec7df328b12b1a40dcab550aef20)

Do let me know if it works. I have updated the README.md to reflect this change.
Thanks, for letting me know.

**Comment by gerrymcjr** [comment]
![capture](https://user-images.githubusercontent.com/8648535/28560225-5c578fca-714c-11e7-9a85-9363e8b123dc.PNG)
i got it running and i think some JS script are missing please also look at the attached photo

i could just download the missing JS files but i think it is necessary to use the JS files that was used in this project as per my experience with web development there are things that wont work with other version

**Comment by malikshubham827** [comment]
Okay I had two folders with the same name one in the global scope, other in js folder so git ignored both instead of only global one. I have included the required files in `public/js/libs`.
You may download `libs` at path `public/js/libs/` in the repo and paste it inside `js` folder and it should work.

**Comment by gerrymcjr** [comment]
![capture](https://user-images.githubusercontent.com/8648535/28562597-7e39d8e2-7155-11e7-96f9-cf8ee44d90eb.PNG)
thank you sorry if there is another issue
![capture](https://user-images.githubusercontent.com/8648535/28562314-565d0764-7154-11e7-8cb7-8b69caa4e2d1.PNG)

also attached is the error shown at command line and also thank you for answering the issue i will continue to run the project and also keep you updated of any other issue

**Comment by malikshubham827** [comment]
First issue is telling that pathlib is not present. Search google how to include this python package on your OS.
I think `pip3 install pathlib` would help, else refer to stackoverflow for your os specific commands.

Try running it in Chrome and see if second error still persists. As I am not getting that error in Chrome. I don't know about [asm.js](http://asmjs.org/).

Don't be sorry, I am glad that you are helping me by telling me mistakes which I would take care of in my future.

**Comment by gerrymcjr** [comment]
![capture](https://user-images.githubusercontent.com/8648535/28598314-5c8fefb2-71d5-11e7-8cdd-c99f5b41dd32.PNG)

the pathlib is already resolved i tried running the project out of the virtual environment but an error is showing the face_recognition module so i ran the project inside the virtual environment then another error cannot find module numpy i tried to install it but the apt-get says it is already installed so i tried pip3 install numpy but still the error is numpy attached is the error

**Comment by gerrymcjr** [comment]
got it working i installed numpy and face_recognition inside the virtual environment i guess that solved my problem

again thank you for the great project it will be an inspiration for me

**Comment by malikshubham827** [comment]
I am glad that you worked it out. It's good because I don't have LINUX OS so, I can now update README.md file that it's working on LINUX also.

**Comment by gerrymcjr** [comment]
and one more thing the facial_recognition,pathlib,openvnc should be installed while on virtual environment  after installing dlib of course

**Comment by malikshubham827** [comment]
Yes, as I have written in my 'How to install' section. See the first point, last sentence. You **have** to activate the virtual environment to follow the subsequent steps, I have bolded it in next commit to gain the reader's attention. I think you missed that and might have mixed it up with global packages.
